import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.scss";
import { useState, useRef } from "react";
import Footer from "../components/Footer";

export default function Home() {
  const Url = [
    {
      id: 1,
      image: "/images/card1.jpg",
      text: "BEACH",
    },
    {
      id: 2,
      image: "/images/card2.jpg",
      text: "NATURE",
    },
    {
      id: 3,
      image: "/images/card3.jpg",
      text: "HOTEL",
    },
    {
      id: 4,
      image: "/images/card4.jpg",
      text: "TRAVEL",
    },
    {
      id: 5,
      image: "/images/card5.jpg",
      text: "MOUNTAIN",
    },
    {
      id: 6,
      image: "/images/card6.jpg",
      text: "WATERFALL",
    },
  ];



  const carousel = useRef(null);

  const [contador, setContador] = useState(1);

  const handleLeftClick = (e) => {
    e.preventDefault();
    console.log(carousel.current.offsetWidth);
    carousel.current.scrollLeft -= carousel.current.offsetWidth / 2;
    if (contador != 1) {
      setContador(contador - 1);
    }
  };

  const handleRightClick = (e) => {
    e.preventDefault();
    console.log(carousel.current.offsetWidth);
    carousel.current.scrollLeft += carousel.current.offsetWidth / 2;
    if (contador != 3) {
      setContador(contador + 1);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <div className={styles.section}>
        <div className={styles.text}>
          <span>Travel website</span>
          <h1>
            NEVER STOP <br></br>EXPLORING THE <br></br> WORLD.
          </h1>
          <p>
            Lorem Ipsum is simply dummy text of the printing and typesetting
            industry. Lorem Ipsum has been the industry standard dummy text ever
            since the 1500s, when an unknown printer took a galley of type and
            scrambled it to make a type specimen book.
          </p>
          <div className={styles.learn}>
            <button>LEARN MORE</button>
          </div>
        </div>
        <div className={styles.areaCarousel}>
          <div className={styles.carousel} ref={carousel}>
            {Url.map((item) => {
              return (
                <>
                  <div className={styles.item}>
                    <div
                      style={{
                        backgroundImage: `url(${item.image})`,
                        backgroundSize: "cover",
                        height: "100%",
                        width: "100%",
                        borderRadius: "20px",
                      }}
                    >
                      <div className={styles.title}>
                        <span>{item.text}</span>
                      </div>
                    </div>
                  </div>
                </>
              );
            })}
          </div>
          <div className={styles.buttons}>
            <button onClick={handleLeftClick}>
              <img src="/images/seta.png" width={30} />
            </button>
            <button onClick={handleRightClick}>
              <img src="/images/seta.png" width={30} />
            </button>
            <div className={styles.separador}></div>
            <span>0{contador}</span>
          </div>
        </div>
      </div>

      <div className={styles.section2}>
        <div className={styles.price}>
          <div className={styles.text}>
            <div className={styles.areaText}>
              <h2>Full Peckage</h2>
              <h1>Your First Choice</h1>
              <h2>From $10k</h2>
              <p>
                Lorem Ipsum is simply dummy text of the printing and typesetting
                industry. Lorem Ipsum has been the industry standard dummy text
                ever since the 1500s
              </p>
              <div className={styles.more}>
                <button>SEE MORE</button>
              </div>
            </div>
          </div>
          <div className={styles.quadro}>
            <div className={styles.quadro1}></div>
          </div>
        </div>

        <div className={styles.about}>
          <div className={styles.section3}>
            <div className={styles.images}>
              <div className={styles.image1}></div>
              <div className={styles.image2}></div>
            </div>
            <div className={styles.aboutUs}>
              <span>
                About <span className={styles.us}>Us</span>
              </span>
              <p>
                Lorem Ipsum is simply dummy text of the printing and typesetting
                industry. Lorem Ipsum has been the industrys standard dummy
                text ever since the 1500s, when an unknown printer took a galley
                of type and scrambled it to make a type specimen book. It has
                survived not only five centuries, but also the leap into
                electronic typesetting, remaining essentially unchanged. It was
                popularised in the 1960s with the release of Letraset sheets
                containing Lorem Ipsum passages, and more recently with desktop
                publishing software like Aldus PageMaker including versions of
                Lorem Ipsum.
              </p>
              <p>
                The standard chunk of Lorem Ipsum used since the 1500s is
                reproduced below for those interested. Sections 1.10.32 and
                1.10.33 from de Finibus Bonorum et Malorum by Cicero are also
                reproduced in their exact original form, accompanied by English
                versions from the 1914 translation by H. Rackham.
              </p>
              <p>
                It is a long established fact that a reader will be distracted
                by the readable content of a page when looking at its layout.
                The point of using Lorem Ipsum is that it has a more-or-less
                normal distribution of letters, as opposed to using Content
                here, content here,
              </p>
              <p>Contrary to popular belief, Lorem Ipsum is not simply</p>

              <div className={styles.read}>
                <button>READ MORE</button>
              </div>
            </div>
            <div className={styles.info}>
              <div className={styles.image3}></div>
              <div className={styles.textArea}>
                <span>Easy &amp; Confident</span>
                <div className={styles.text}>Estate Aewsome</div>
                <p>
                  Sed ut perspiciatis unde omnis iste natus error sit voluptatem
                  accusantium doloremque, totam reem aperiam.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className={styles.section4}>
        <div className={styles.box}>
          <div className={styles.title}>Let is Stay in Touch</div>
          <div className={styles.subtitle}>Enjoy 15% off your first order when you goin our mailing list.</div>
          <div className={styles.inputArea}>
            <input type="email" placeholder="Enter your e-mail address"/>
            <button type="submit">Subscribe</button>
          </div>
          <div className={styles.ward}>
            We respect your privacy, so we never share your info.
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
}
